### PR TITLE
linked example files in example readme

### PR DESCRIPTION
**Pull request by Cs137**
Hi Nico,

I thought it's handy to have the examples linked to the corresponding headings in the example readme, and introduced such links. Feel free to add them if you think others might benefit from it as well.

Best regards & happy new year,
Christian

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Yes that's handy thank you. While you're at it, I suggest renaming 00.py in 00-do-something.py, a bit like the last ones are, so the filename is more informative.

**Comment by Cs137** [comment]
I added descriptive filenames for examples 00 to 08, and hope they match your expectations. 

Cheers

**Review by NicolasCARPi — APPROVED** [review]
Great, thank you very much!

**Comment by Cs137** [comment]
My pleasure, thank you!

**Pull request merged**
