### PR TITLE
Add example that shows how to handle date-time formats

### PR DESCRIPTION
**Pull request by mhxion**
As promised in [#4543](https://github.com/elabftw/elabftw/pull/4543), this example shows how to convert string date-time outputs to proper Python `datetime` objects 🙂

### CODE REVIEW

**Review by NicolasCARPi — CHANGES_REQUESTED** [review]
You should rename the file to 10-date-time-conversions.py. (I just pushed 09 a few minutes ago :zany_face: )

From the beginning, try and explain every import. For instance add "we will use pandas for dealing with tabular data", "we will use seaborn to plot the result", "ast is necessary because....". Think about the reader being super unfamiliar with anything python related.

run "black --skip-string-normalization", run "isort" (should be a github action ideally)

Otherwise the main content is heavily commented which is great!

**Review by NicolasCARPi — CHANGES_REQUESTED** [review]
* Add a line in the `examples/README.md` to explain what it is.
* chmod +x the file
* Running it gives this error:

~~~
Traceback (most recent call last):
  File "/home/ktr/.dev/elabapi-python/examples/./10-date-time-conversions.py", line 46, in <module>
    st_data = ast.literal_eval(str(data))  # ast safely serializes our experiments data to dict
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 110, in literal_eval
    return _convert(node_or_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 90, in _convert
    return list(map(_convert, node.elts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 99, in _convert
    return dict(zip(map(_convert, node.keys),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 109, in _convert
    return _convert_signed_num(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 83, in _convert_signed_num
    return _convert_num(node)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 74, in _convert_num
    _raise_malformed_node(node)
  File "/usr/lib/python3.11/ast.py", line 71, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 11: <ast.Call object at 0x7f8aa69cfb50>
~~~

Also, I'm not sure why you use this in the first place. What's wrong with accessing the value with `data[0].created_at`?

**Comment by mhxion** [comment]
> You should rename the file to 10-date-time-conversions.py. (I just pushed 09 a few minutes ago 🤪 )
That's the second clash with you today lol :D

> Think about the reader being super unfamiliar with anything python related.
Alright!

**Comment by mhxion** [comment]
> Running it gives this error:

That's strange. I just ran it on my machine once more. I believe that means there's some data that's being returned by your elabftw that `ast` doesn't know how to handle.
Screenshot 2023-09-01 at 6 27 13 PM

But if that's the case I will avoid putting `ast` then.

> Also, I'm not sure why you use this in the first place. What's wrong with accessing the value with data[0].created_at?

Mainly to get a proper dictionary so manipulating it gets easier.

**Comment by mhxion** [comment]
Fixed all aforementioned issues. Squashed the commits.

**Comment by NicolasCARPi** [comment]
Yeah so the issue was that I was using the old lib which still returned datetime objects, hence the issue with ast.

I'd like for the script to actually show the plot at the end. Here it doesn't show anything. After installing `tk` on my computer, I could show the plot by importing matplotlib and doing `plt.show()`, but maybe seaborn can call it directly? Does the plot show directly on your computer? Are you using the script in a notebook context? I'm just using plain old terminal. In fact, this repo could also host jupyter notebooks, it could be interesting to better explain some scripting!

**Comment by mhxion** [comment]
> Yeah so the issue was that I was using the old lib which still returned datetime objects, hence the issue with ast.

Happened with me a couple of times before :) I left the code unchanged and added comments on how to convert to dictionary using `ast`.

> I could show the plot by importing matplotlib and doing plt.show(), but maybe seaborn can call it directly? Does the plot show directly on your computer?

Actually it doesn't. Good catch. I was doing it on Jupyter notebook. I assumed `seaborn` implicitly calls `plt.show()` but it doesn't. That was Notebook magic. I just added `plt.show()`.

> In fact, this repo could also host jupyter notebooks, it could be interesting to better explain some scripting!

I am glad to know that you find this interesting. I don't mind either way whether to upload this as a `.py` or Jupyter Notebook. I was thinking of adding the final image as well which would probably help capture some attention to the usefulness of the API. However, I am limited on permission to share any internal data, which means I can't show any plots, which would defeat the benefit of using notebook. I can try creating randomized year data for the dataframe and not show the user how I got the dataframe and then plot the graph ;) and upload the whole thing inside the notebook. 

The `.py` script as it is right now should produce the plot (also it should work without `tk`). Let me know which way you prefer.

**Review by NicolasCARPi — APPROVED** [review]
Yay it works now. There is one thing you forgot, is to chmod +x the file, but it's okay I'll do it ;)

**Comment by NicolasCARPi** [comment]
Regarding notebook and images, I believe github shows the html of notebooks ([example](https://github.com/ibm-et/jupyter-samples/blob/master/elasticity/Elasticity%20Experiment.ipynb)), so it really would be nice to have a few in here.

As for the data, you can (and should) use `bin/console dev:populate src/tools/populate-config.yml.dist` on a dev instance so it populates fake data and you can show plots from that ;) Don't do this in prod!!!

**Comment by mhxion** [comment]
> Yay it works now. There is one thing you forgot, is to chmod +x the file, but it's okay I'll do it ;)

Glad to know. And thank you!

**Comment by mhxion** [comment]
> I believe github shows the html of notebooks ([example](https://github.com/ibm-et/jupyter-samples/blob/master/elasticity/Elasticity%20Experiment.ipynb)), so it really would be nice to have a few in here.

Will keep that in mind for future  contributions :)

> you can (and should) use `bin/console dev:populate src/tools/populate-config.yml.dist` on a dev instance

I didn't know about that! Thanks.

**Pull request merged**
